# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calculator(object):
    def setupUi(self, calculator):
        calculator.setObjectName("calculator")
        calculator.resize(338, 185)
        self.verticalLayout = QtWidgets.QVBoxLayout(calculator)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(calculator)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_solve = QtWidgets.QPushButton(calculator)
        self.btn_solve.setStyleSheet("QPushButton {\n"
"    background-color: rgb(72, 72, 72);\n"
"    color: #f0f0f0;\n"
"}")
        self.btn_solve.setObjectName("btn_solve")
        self.gridLayout.addWidget(self.btn_solve, 4, 3, 1, 1)
        self.btn_multiply = QtWidgets.QPushButton(calculator)
        self.btn_multiply.setObjectName("btn_multiply")
        self.gridLayout.addWidget(self.btn_multiply, 3, 3, 1, 1)
        self.btn_dot = QtWidgets.QPushButton(calculator)
        self.btn_dot.setObjectName("btn_dot")
        self.gridLayout.addWidget(self.btn_dot, 4, 2, 1, 1)
        self.btn_seven = QtWidgets.QPushButton(calculator)
        self.btn_seven.setObjectName("btn_seven")
        self.gridLayout.addWidget(self.btn_seven, 1, 0, 1, 1)
        self.btn_eight = QtWidgets.QPushButton(calculator)
        self.btn_eight.setObjectName("btn_eight")
        self.gridLayout.addWidget(self.btn_eight, 1, 1, 1, 1)
        self.btn_sixth = QtWidgets.QPushButton(calculator)
        self.btn_sixth.setObjectName("btn_sixth")
        self.gridLayout.addWidget(self.btn_sixth, 2, 2, 1, 1)
        self.btn_four = QtWidgets.QPushButton(calculator)
        self.btn_four.setObjectName("btn_four")
        self.gridLayout.addWidget(self.btn_four, 2, 0, 1, 1)
        self.btn_five = QtWidgets.QPushButton(calculator)
        self.btn_five.setObjectName("btn_five")
        self.gridLayout.addWidget(self.btn_five, 2, 1, 1, 1)
        self.btn_nine = QtWidgets.QPushButton(calculator)
        self.btn_nine.setObjectName("btn_nine")
        self.gridLayout.addWidget(self.btn_nine, 1, 2, 1, 1)
        self.btn_one = QtWidgets.QPushButton(calculator)
        self.btn_one.setObjectName("btn_one")
        self.gridLayout.addWidget(self.btn_one, 3, 0, 1, 1)
        self.btn_divide = QtWidgets.QPushButton(calculator)
        self.btn_divide.setObjectName("btn_divide")
        self.gridLayout.addWidget(self.btn_divide, 2, 3, 1, 1)
        self.btn_two = QtWidgets.QPushButton(calculator)
        self.btn_two.setObjectName("btn_two")
        self.gridLayout.addWidget(self.btn_two, 3, 1, 1, 1)
        self.btn_three = QtWidgets.QPushButton(calculator)
        self.btn_three.setObjectName("btn_three")
        self.gridLayout.addWidget(self.btn_three, 3, 2, 1, 1)
        self.btn_minus = QtWidgets.QPushButton(calculator)
        self.btn_minus.setObjectName("btn_minus")
        self.gridLayout.addWidget(self.btn_minus, 1, 3, 1, 1)
        self.btn_zero = QtWidgets.QPushButton(calculator)
        self.btn_zero.setObjectName("btn_zero")
        self.gridLayout.addWidget(self.btn_zero, 4, 0, 1, 2)
        self.btn_clear = QtWidgets.QPushButton(calculator)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout.addWidget(self.btn_clear, 0, 0, 1, 1)
        self.btn_back = QtWidgets.QPushButton(calculator)
        self.btn_back.setObjectName("btn_back")
        self.gridLayout.addWidget(self.btn_back, 0, 1, 1, 1)
        self.btn_degree = QtWidgets.QPushButton(calculator)
        self.btn_degree.setObjectName("btn_degree")
        self.gridLayout.addWidget(self.btn_degree, 0, 2, 1, 1)
        self.btn_plus = QtWidgets.QPushButton(calculator)
        self.btn_plus.setObjectName("btn_plus")
        self.gridLayout.addWidget(self.btn_plus, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(calculator)
        QtCore.QMetaObject.connectSlotsByName(calculator)

    def retranslateUi(self, calculator):
        _translate = QtCore.QCoreApplication.translate
        calculator.setWindowTitle(_translate("calculator", "Калькулятор"))
        self.btn_solve.setText(_translate("calculator", "="))
        self.btn_multiply.setText(_translate("calculator", "*"))
        self.btn_dot.setText(_translate("calculator", "."))
        self.btn_seven.setText(_translate("calculator", "7"))
        self.btn_eight.setText(_translate("calculator", "8"))
        self.btn_sixth.setText(_translate("calculator", "6"))
        self.btn_four.setText(_translate("calculator", "4"))
        self.btn_five.setText(_translate("calculator", "5"))
        self.btn_nine.setText(_translate("calculator", "9"))
        self.btn_one.setText(_translate("calculator", "1"))
        self.btn_divide.setText(_translate("calculator", "/"))
        self.btn_two.setText(_translate("calculator", "2"))
        self.btn_three.setText(_translate("calculator", "3"))
        self.btn_minus.setText(_translate("calculator", "-"))
        self.btn_zero.setText(_translate("calculator", "0"))
        self.btn_clear.setText(_translate("calculator", "X"))
        self.btn_back.setText(_translate("calculator", "<-"))
        self.btn_degree.setText(_translate("calculator", "x^2"))
        self.btn_plus.setText(_translate("calculator", "+"))
